local nvim_web_devicon = require 'nvim-web-devicons'
local alphabet

local normal_font = {
  a = 'a',
  b = 'b',
  c = 'c',
  d = 'd',
  e = 'e',
  f = 'f',
  g = 'g',
  h = 'h',
  i = 'i',
  j = 'j',
  k = 'k',
  l = 'l',
  m = 'm',
  n = 'n',
  o = 'o',
  p = 'p',
  q = 'q',
  r = 'r',
  s = 's',
  t = 't',
  u = 'u',
  v = 'v',
  w = 'w',
  x = 'x',
  y = 'y',
  z = 'z',
}

alphabet = normal_font

local black_square_font = {
  a = '🅰 ',
  b = '🅱 ',
  c = '🅲 ',
  d = '🅳 ',
  e = '🅴 ',
  f = '🅵 ',
  g = '🅶 ',
  h = '🅷 ',
  i = '🅸 ',
  j = '🅹 ',
  k = '🅺 ',
  l = '🅻 ',
  m = '🅼 ',
  n = '🅽 ',
  o = '🅾 ',
  p = '🅿 ',
  q = '🆀 ',
  r = '🆁 ',
  s = '🆂 ',
  t = '🆃 ',
  u = '🆄 ',
  v = '🆅 ',
  w = '🆆 ',
  x = '🆇 ',
  y = '🆈 ',
  z = '🆉 ',
}

local double_struck_font = {
  a = '𝕒 ',
  b = '𝕓 ',
  c = '𝕔 ',
  d = '𝕕 ',
  e = '𝕖 ',
  f = '𝕗 ',
  g = '𝕘 ',
  h = '𝕙 ',
  i = '𝕚 ',
  j = '𝕛 ',
  k = '𝕜 ',
  l = '𝕝 ',
  m = '𝕞 ',
  n = '𝕟 ',
  o = '𝕠 ',
  p = '𝕡 ',
  q = '𝕢 ',
  r = '𝕣 ',
  s = '𝕤 ',
  t = '𝕥 ',
  u = '𝕦 ',
  v = '𝕧 ',
  w = '𝕨 ',
  x = '𝕩 ',
  y = '𝕪 ',
  z = '𝕫 ',
}

local square_font = {
  a = '🄰 ',
  b = '🄱 ',
  c = '🄲 ',
  d = '🄳 ',
  e = '🄴 ',
  f = '🄵 ',
  g = '🄶 ',
  h = '🄷 ',
  i = '🄸 ',
  j = '🄹 ',
  k = '🄺 ',
  l = '🄻 ',
  m = '🄼 ',
  n = '🄽 ',
  o = '🄾 ',
  p = '🄿 ',
  q = '🅀 ',
  r = '🅁 ',
  s = '🅂 ',
  t = '🅃 ',
  u = '🅄 ',
  v = '🅅 ',
  w = '🅆 ',
  x = '🅇 ',
  y = '🅈 ',
  z = '🅉 ',
}
local fancy_style_17_font = {
  a = 'ᗅ ',
  b = 'ᙘ ',
  c = 'ᑤ ',
  d = 'ᗫ ',
  e = 'ᙍ ',
  f = 'ᖴ ',
  g = 'ᘜ ',
  h = 'ᕼ ',
  i = 'ᓿ ',
  j = 'ᒙ ',
  k = 'ᖽᐸ ',
  l = 'ᒪ ',
  m = 'ᙢ ',
  n = 'ᘉ ',
  o = 'ᓎ ',
  p = 'ᕿ ',
  q = 'ᕴ ',
  r = 'ᖇ ',
  s = 'S ',
  t = 'ᖶ ',
  u = 'ᑗ ',
  v = 'ᐻ ',
  w = 'ᙎ ',
  x = '᙭ ',
  y = 'ᖻ ',
  z = 'ᙣ ',
}
local bold_italic_font = {
  a = '𝙖 ',
  b = '𝙗 ',
  c = '𝙘 ',
  d = '𝙙 ',
  e = '𝙚 ',
  f = '𝙛 ',
  g = '𝙜 ',
  h = '𝙝 ',
  i = '𝙞 ',
  j = '𝙟 ',
  k = '𝙠 ',
  l = '𝙡 ',
  m = '𝙢 ',
  n = '𝙣 ',
  o = '𝙤 ',
  p = '𝙥 ',
  q = '𝙦 ',
  r = '𝙧 ',
  s = '𝙨 ',
  t = '𝙩 ',
  u = '𝙪 ',
  v = '𝙫 ',
  w = '𝙬 ',
  x = '𝙭 ',
  y = '𝙮 ',
  z = '𝙯 ',
}
local fancy_style_19_font = {
  a = 'ꁲ',
  b = 'ꃳ',
  c = 'ꏳ',
  d = 'ꀷ',
  e = 'ꑀ',
  f = 'ꊯ',
  g = 'ꁅ',
  h = 'ꁝ',
  i = '꒐',
  j = '꒑',
  k = 'ꈵ',
  l = '꒒',
  m = 'ꂵ',
  n = 'ꃔ',
  o = 'ꊿ',
  p = 'ꉣ',
  q = 'ꋠ',
  r = 'ꌅ',
  s = 'ꈜ',
  t = 'ꋖ',
  u = 'ꌈ',
  v = '꒦',
  w = 'ꅐ',
  x = 'ꉤ',
  y = 'ꐔ',
  z = 'ꑒ',
}

local emoji = {
  DevIconDefault = '📄',
  DevIconAvif = '📸',
  DevIconBSPWM = '🖥️',
  DevIconBabelrc = '🚀',
  DevIconBashProfile = '🖋️',
  DevIconBashrc = '💻',
  DevIconBazelBuild = '🏗️',
  DevIconBazelWorkspace = '📂',
  DevIconBrewfile = '🍺',
  DevIconCMakeLists = '🛠️',
  DevIconCantorrc = '📜',
  DevIconCheckhealth = '🧑‍⚕️',
  DevIconCodeOfConduct = '📖',
  DevIconCommitlintConfig = '✅',
  DevIconConfig = '⚙️',
  -- DevIconDockerfile = '🐋',
  DevIconDsStore = '🗂️',
  DevIconEditorConfig = '🖊️',
  -- DevIconEnv = '🌍',
  DevIconEslintIgnore = '🚫',
  DevIconEslintrc = '🔍',
  DevIconFavicon = '🌟',
  DevIconFreeCADConfig = '📐',
  -- DevIconGTK = '🎨',
  DevIconGemfile = '💎',
  DevIconGitAttributes = '📄',
  DevIconGitBlameIgnore = '🙈',
  DevIconGitCommit = '✍️',
  DevIconGitConfig = '🔧',
  DevIconGitIgnore = '🚫',
  DevIconGitModules = '🧩',
  DevIconGitlabCI = '🤖',
  DevIconGoMod = '📚',
  DevIconGoSum = '🧮',
  DevIconGoWork = '🔨',
  DevIconGradleBuildScript = '📜',
  DevIconGradleProperties = '📋',
  DevIconGradleSettings = '⚙️',
  DevIconGradleWrapperProperties = '🗒️',
  DevIconGradleWrapperScript = '📜',
  DevIconGruntfile = '🐗',
  DevIconGulpfile = '🥤',
  DevIconGvimrc = '🖋️',
  DevIconHypridle = '🌉',
  DevIconHyprland = '🏞️',
  DevIconHyprlock = '🔒',
  DevIconHyprpaper = '🖼️',
  DevIconI18nConfig = '🌐',
  DevIconIonic = '🔵',
  DevIconJustfile = '📄',
  DevIconKDEglobals = '🌎',
  DevIconKalgebrarc = '➕',
  DevIconKdenliveLayoutsrc = '🎬',
  DevIconKdenliverc = '🎥',
  DevIconKiCadCache = '🗂️',
  DevIconKiCadFootprintTable = '🦶',
  DevIconKiCadSymbolTable = '🔣',
  DevIconKritadisplayrc = '🖼️',
  DevIconKritarc = '🎨',
  DevIconLXDEConfigFile = '📂',
  DevIconLXQtConfigFile = '🛠️',
  -- DevIconLicense = '📜',
  DevIconLuaurc = '🌀',
  DevIconMailmap = '📬',
  DevIconMakefile = '🛠️',
  DevIconMaven = '🍵',
  DevIconMixLock = '🔒',
  DevIconMpv = '📹',
  DevIconNPMIgnore = '🚫',
  DevIconNPMrc = '🔧',
  DevIconNodeModules = '📦',
  DevIconNuxtConfig = '🟢',
  DevIconPKGBUILD = '📦',
  DevIconPackageJson = '📜',
  DevIconPackageLockJson = '🔒',
  DevIconPlatformio = '⚙️',
  DevIconPrettierConfig = '💅',
  DevIconPrettierIgnore = '🚫',
  DevIconProcfile = '📃',
  -- DevIconPy.typed = '🐍',
  -- DevIconQt = '📱',
  DevIconRakefile = '🛠️',
  -- DevIconRmd = '📘',
  DevIconRobotsTxt = '🤖',
  DevIconSRCINFO = '📜',
  DevIconSecurity = '🛡️',
  DevIconSettingsJson = '⚙️',
  DevIconSvelteConfig = '🟠',
  DevIconTSConfig = '📘',
  DevIconTailwindConfig = '🌬️',
  -- DevIconTmux = '🖥️',
  DevIconTypoScriptSetup = '📑',
  DevIconVLC = '🎥',
  DevIconVagrantfile = '📦',
  DevIconVercel = '⚡',
  DevIconVimrc = '🖋️',
  DevIconWebpack = '📦',
  DevIconWeston = '🖥️',
  DevIconXInitrc = '📂',
  DevIconXSettingsdConf = '⚙️',
  DevIconXauthority = '🔒',
  DevIconXorgConf = '🖥️',
  DevIconXresources = '📜',
  DevIconXsession = '🖥️',
  DevIconZigObjectNotation = '🟡',
  DevIconZshenv = '💻',
  DevIconZshprofile = '🖋️',
  DevIconZshrc = '💻',
  DevIconi3 = '🏠',
  DevIconnode = '🟩',
  DevIconxmonad = '🧱',
  DevIcon3DObjectFile = '📐',
  DevIcon3gp = '🎥',
  DevIcon7z = '🗜️',
  DevIconAPL = '🧮',
  DevIconAdvancedAudioCoding = '🎵',
  DevIconAi = '🎨',
  DevIconAndroid = '🤖',
  DevIconAppleScript = '🍎',
  DevIconArduino = '🔵',
  DevIconAsc = '📜',
  DevIconAsciinema = '🎥',
  DevIconAss = '💬',
  DevIconAstro = '🌌',
  DevIconAudioInterchangeFileFormat = '🎵',
  DevIconAutoCADDwg = '📐',
  DevIconAutoCADDxf = '📏',
  DevIconAwk = '📝',
  DevIconAzureCli = '☁️',
  DevIconBQN = '🔣',
  DevIconBackup = '📦',
  DevIconBash = '💻',
  DevIconBat = '📜',
  DevIconBazel = '🏗️',
  DevIconBibTeX = '📚',
  DevIconBicep = '💪',
  DevIconBicepParameters = '⚙️',
  DevIconBin = '🗑️',
  DevIconBinaryGLTF = '📦',
  DevIconBlade = '🔪',
  DevIconBlender = '🍹',
  DevIconBlueprint = '📘',
  DevIconBmp = '🖼️',
  DevIconBoundaryRepresentation = '📐',
  DevIconBz = '🗜️',
  DevIconBz2 = '🗜️',
  DevIconBz3 = '🗜️',
  DevIconBzl = '⚙️',
  DevIconC = '🔵',
  DevIconCMake = '🛠️',
  DevIconCPlusPlus = '➕',
  DevIconCPlusPlusModule = '📦',
  DevIconCSharpProject = '🎵',
  DevIconCache = '📂',
  DevIconCjs = '📜',
  DevIconClojure = '🍃',
  DevIconClojureC = '🌿',
  DevIconClojureJS = '🌿',
  DevIconCobol = '🏢',
  DevIconCoffee = '☕',
  DevIconConf = '⚙️',
  DevIconConfigRu = '📜',
  DevIconConfiguration = '⚙️',
  DevIconCowsayFile = '🐄',
  DevIconCp = '📄',
  DevIconCpp = '➕',
  DevIconCppm = '📦',
  DevIconCrdownload = '📥',
  DevIconCrystal = '💎',
  DevIconCs = '🎵',
  DevIconCsh = '💻',
  DevIconCson = '📜',
  DevIconCss = '🎨',
  DevIconCsv = '📊',
  DevIconCts = '📘',
  DevIconCue = '🎵',
  DevIconCxx = '➕',
  DevIconCxxm = '📦',
  DevIconD = '🟥',
  DevIconDart = '🎯',
  DevIconDb = '📚',
  DevIconDconf = '⚙️',
  DevIconDesktopEntry = '💻',
  DevIconDiff = '🔀',
  DevIconDll = '🔌',
  DevIconDoc = '📄',
  -- DevIconDockerfile = '🐋',
  DevIconDocx = '📄',
  DevIconDot = '⚫',
  DevIconDownload = '⬇️',
  DevIconDrools = '📜',
  DevIconDropbox = '📦',
  DevIconDump = '🗑️',
  DevIconEbook = '📚',
  DevIconEdn = '🔣',
  DevIconEex = '📜',
  DevIconElf = '🧝',
  DevIconElisp = '📜',
  DevIconElm = '🌳',
  DevIconEmbeddedOpenTypeFont = '🔤',
  -- DevIconEnv = '🌍',
  DevIconEpp = '📜',
  DevIconEpub = '📚',
  DevIconErb = '📜',
  DevIconErl = '🤖',
  DevIconEx = '✨',
  DevIconExe = '⚙️',
  DevIconExs = '✨',
  DevIconFIGletFontControl = '🔠',
  DevIconFIGletFontFormat = '🔡',
  DevIconFdmdownload = '⬇️',
  DevIconFennel = '🌿',
  DevIconFish = '🐟',
  DevIconFortran = '🔢',
  DevIconFreeCAD = '📐',
  DevIconFreeLosslessAudioCodec = '🎵',
  DevIconFs = '📜',
  DevIconFsharp = '🎼',
  DevIconFsi = '📜',
  DevIconFsscript = '📜',
  DevIconFsx = '📜',
  DevIconFusion360 = '🌐',
  DevIconGCode = '🛠️',
  DevIconGDScript = '📝',
  DevIconGIMP = '🎨',
  -- DevIconGTK = '🎨',
  DevIconGemspec = '💎',
  DevIconGentooBuild = '🐧',
  DevIconGif = '🎞️',
  DevIconGitLogo = '🔗',
  DevIconGleam = '✨',
  DevIconGo = '🟦',
  DevIconGodotProject = '🎭',
  DevIconGodotTextResource = '📜',
  DevIconGodotTextScene = '🎬',
  DevIconGraphQL = '🔗',
  DevIconGv = '📊',
  DevIconGz = '🗜️',
  DevIconH = '📝',
  DevIconHTTP = '🌐',
  DevIconHaml = '📜',
  DevIconHaxe = '🛠️',
  DevIconHbs = '🎭',
  DevIconHeex = '📜',
  DevIconHexadecimal = '🔢',
  DevIconHh = '💻',
  DevIconHpp = '📄',
  DevIconHrl = '⚙️',
  DevIconHs = '🔣',
  DevIconHtm = '🌐',
  DevIconHtml = '🌐',
  DevIconHuff = '⚡',
  DevIconHurl = '🌐',
  DevIconHxx = '📄',
  DevIconIcal = '📅',
  DevIconIcalendar = '📅',
  DevIconIco = '🖼️',
  DevIconIcs = '📅',
  DevIconIfb = '📂',
  DevIconIfc = '🏗️',
  DevIconIge = '📏',
  DevIconIges = '📏',
  DevIconIgs = '📏',
  DevIconImage = '🖼️',
  DevIconImg = '🖼️',
  DevIconImportConfiguration = '📜',
  DevIconInfo = 'ℹ️',
  DevIconIni = '⚙️',
  DevIconIso = '💿',
  DevIconIxx = '📜',
  DevIconJWM = '🖥️',
  DevIconJava = '☕',
  DevIconJavaScriptReactSpec = '⚛️',
  DevIconJavaScriptReactTest = '⚛️',
  DevIconJpeg = '🖼️',
  DevIconJpegXl = '🖼️',
  DevIconJpg = '🖼️',
  DevIconJs = '⚡',
  DevIconJson = '📊',
  DevIconJson5 = '📊',
  DevIconJsonc = '📊',
  DevIconJsx = '⚛️',
  DevIconKbx = '🔒',
  DevIconKdb = '📚',
  DevIconKdbx = '📚',
  DevIconKdenlive = '🎬',
  DevIconKiCad = '📐',
  DevIconKotlin = '⚛️',
  DevIconKotlinScript = '⚛️',
  DevIconKrita = '🎨',
  DevIconKsh = '💻',
  DevIconLeex = '📜',
  DevIconLess = '📝',
  DevIconLhs = '📜',
  DevIconLib = '📚',
  DevIconLibrecadFontFile = '📏',
  -- DevIconLicense = '📜',
  DevIconLinuxKernelObject = '🐧',
  DevIconLiquid = '💧',
  DevIconLocalization = '🌍',
  DevIconLock = '🔒',
  DevIconLog = '📜',
  DevIconLogos = '📄',
  DevIconLrc = '🎵',
  DevIconLua = '🌀',
  DevIconLuau = '🏖️',
  DevIconM3u = '🎶',
  DevIconM3u8 = '🎶',
  DevIconM4V = '🎥',
  DevIconMOV = '🎥',
  DevIconMPEG4 = '🎬',
  DevIconMPEGAudioLayerIII = '🎶',
  DevIconMagnet = '🧲',
  DevIconMarkdown = '📖',
  DevIconMaterial = '📦',
  DevIconMd = '📖',
  DevIconMd5 = '🔒',
  DevIconMdx = '📖',
  DevIconMint = '🌿',
  DevIconMjs = '⚡',
  DevIconMkv = '🎥',
  DevIconMl = '🤖',
  DevIconMli = '💻',
  DevIconMobi = '📱',
  DevIconMojo = '🔮',
  DevIconMonkeysAudio = '🎵',
  DevIconMotoko = '🍃',
  DevIconMp4 = '🎬',
  DevIconMpp = '🎬',
  DevIconMts = '🎥',
  DevIconMustache = '🧔',
  DevIconNfo = '📜',
  DevIconNim = '🦸',
  DevIconNix = '🐧',
  DevIconNotebook = '📒',
  DevIconNswag = '🔧',
  DevIconNushell = '💻',
  DevIconObjectFile = '📦',
  DevIconObjectiveC = '🖥️',
  DevIconObjectiveCPlusPlus = '➕',
  DevIconOggVorbis = '🎵',
  DevIconOpenSCAD = '🛠️',
  DevIconOpenTypeFont = '🔤',
  DevIconOpusAudioFile = '🎶',
  DevIconOrgMode = '📅',
  DevIconOut = '⬇️',
  DevIconPackedResource = '📦',
  DevIconPart = '📦',
  DevIconPatch = '🔨',
  DevIconPdf = '📄',
  DevIconPhp = '🐘',
  DevIconPls = '📜',
  DevIconPm = '📜',
  DevIconPng = '🖼️',
  DevIconPp = '📄',
  DevIconPpt = '📊',
  DevIconPrisma = '🎨',
  DevIconProlog = '🧠',
  DevIconPsManifestfile = '📜',
  DevIconPsScriptModulefile = '📜',
  DevIconPsScriptfile = '📜',
  DevIconPsb = '🖼️',
  DevIconPsd = '🖼️',
  DevIconPub = '📚',
  DevIconPulseCodeModulation = '🎶',
  DevIconPxd = '📦',
  DevIconPxi = '📦',
  DevIconPy = '🐍',
  DevIconPyc = '🐍',
  DevIconPyd = '🐍',
  DevIconPyi = '🐍',
  DevIconPyo = '🐍',
  DevIconPyw = '🐍',
  DevIconPyx = '🐍',
  -- DevIconQt = '🔲',
  DevIconQuery = '🔍',
  DevIconR = '📊',
  DevIconRake = '🔧',
  DevIconRar = '🗜️',
  DevIconRazorPage = '⚙️',
  DevIconRb = '💎',
  DevIconReScript = '🔧',
  DevIconReScriptInterface = '🔧',
  DevIconRlib = '📚',
  -- DevIconRmd = '📄',
  DevIconRproj = '📂',
  DevIconRs = '🦀',
  DevIconRss = '📡',
  DevIconSass = '🎨',
  DevIconScala = '⚙️',
  DevIconScheme = '🔣',
  DevIconScss = '🎨',
  DevIconSh = '💻',
  DevIconSha1 = '🔒',
  DevIconSha224 = '🔒',
  DevIconSha256 = '🔒',
  DevIconSha384 = '🔒',
  DevIconSha512 = '🔒',
  DevIconSharedObject = '📦',
  DevIconSig = '🖊️',
  DevIconSignature = '🖊️',
  DevIconSketchUp = '🛠️',
  DevIconSlim = '📜',
  DevIconSln = '📂',
  DevIconSml = '📜',
  DevIconSolidWorksAsm = '⚙️',
  DevIconSolidWorksPrt = '⚙️',
  DevIconSolidity = '💎',
  DevIconSolveSpace = '🛠️',
  DevIconSpecJs = '⚡',
  DevIconSpecTs = '🔧',
  DevIconSql = '📊',
  DevIconSrt = '🎬',
  DevIconSsa = '📜',
  DevIconStaticLibraryArchive = '📚',
  DevIconSte = '📦',
  DevIconStep = '📐',
  DevIconStp = '📐',
  DevIconStyl = '🎨',
  DevIconSub = '📤',
  DevIconSublime = '🖋️',
  DevIconSuo = '📂',
  DevIconSvelte = '⚛️',
  DevIconSvg = '🖼️',
  DevIconSwift = '🍏',
  DevIconSystemVerilog = '📟',
  DevIconTFVars = '📝',
  DevIconTcl = '💻',
  DevIconTempl = '📄',
  DevIconTerraform = '🌍',
  DevIconTestJs = '⚡',
  DevIconTestTs = '🔧',
  DevIconTex = '📚',
  DevIconTgz = '🗜️',
  DevIconThunderbird = '🐦',
  -- DevIconTmux = '🖥️',
  DevIconToml = '📄',
  DevIconTor = '🕵️‍♂️',
  DevIconTorrent = '🌐',
  DevIconTrueTypeFont = '🔤',
  DevIconTsx = '⚛️',
  DevIconTwig = '🌿',
  DevIconTxt = '📄',
  DevIconTxz = '🗜️',
  DevIconTypeScript = '⚡',
  DevIconTypeScriptDeclaration = '⚡',
  DevIconTypeScriptReactSpec = '⚛️',
  DevIconTypeScriptReactTest = '⚛️',
  DevIconTypoScript = '📝',
  DevIconTypoScriptConfig = '⚙️',
  DevIconUI = '🎨',
  DevIconVHDL = '🖥️',
  DevIconVRML = '🎮',
  DevIconVala = '🐒',
  DevIconVerilog = '💻',
  DevIconVim = '🖋️',
  DevIconVlang = '💻',
  DevIconVsix = '📦',
  DevIconVue = '🔮',
  DevIconWasm = '🌐',
  DevIconWavPack = '🎶',
  DevIconWavPackCorrection = '🎶',
  DevIconWaveformAudioFile = '🎶',
  DevIconWebOpenFontFormat = '🔤',
  DevIconWebm = '🎥',
  DevIconWebmanifest = '📄',
  DevIconWebp = '🖼️',
  -- DevIconWebpack = '⚙️',
  DevIconXaml = '📝',
  DevIconXcLocalization = '🌐',
  DevIconXcPlayground = '🎮',
  DevIconXls = '📊',
  DevIconXlsx = '📊',
  DevIconXml = '📜',
  DevIconXpi = '📦',
  DevIconXul = '🖥️',
  DevIconXz = '🗜️',
  DevIconYaml = '📜',
  DevIconYml = '📜',
  DevIconZig = '⚡',
  DevIconZip = '🗜️',
  DevIconZsh = '💻',
  DevIconZst = '🗜️',
  DevIconapk = '📱',
  DevIconcuda = '💻',
  DevIconcudah = '💻',
  DevIconsbt = '📝',
  DevIconAOSC = '🐧',
  DevIconAlmalinux = '🐧',
  DevIconAlpine = '🐧',
  DevIconApple = '🍏',
  DevIconArch = '🐧',
  DevIconArchcraft = '🐧',
  DevIconArchlabs = '🐧',
  DevIconArcoLinux = '🐧',
  DevIconArtix = '🐧',
  DevIconBigLinux = '🐧',
  DevIconCentos = '🐧',
  DevIconCrystalLinux = '🐧',
  DevIconDebian = '🐧',
  DevIconDeepin = '🐧',
  DevIconDevuan = '🐧',
  DevIconElementary = '🐧',
  DevIconEndeavour = '🐧',
  DevIconFedora = '🐧',
  DevIconFreeBSD = '🐧',
  DevIconGarudaLinux = '🐧',
  DevIconGuix = '🐧',
  DevIconHyperbolaGNULinuxLibre = '🐧',
  DevIconIllumos = '🖥️',
  DevIconKDEneon = '🌈',
  DevIconKali = '⚡',
  DevIconKubuntu = '🐧',
  DevIconLXLE = '🐧',
  DevIconLinux = '🐧',
  DevIconLocOS = '🐧',
  DevIconMXLinux = '🐧',
  DevIconMageia = '🐧',
  DevIconManjaro = '🐧',
  -- DevIconMint = '🍃',
  DevIconNixOS = '🐧',
  DevIconOpenBSD = '🐧',
  DevIconParabolaGNULinuxLibre = '🐧',
  DevIconParrot = '🦜',
  DevIconPop_OS = '🌟',
  DevIconPuppyLinux = '🐶',
  DevIconQubesOS = '🖥️',
  DevIconRaspberryPiOS = '🍓',
  DevIconRedhat = '🐧',
  DevIconRockyLinux = '🐧',
  DevIconSabayon = '🐧',
  DevIconSlackware = '🐧',
  DevIconSolus = '🐧',
  DevIconTails = '🐾',
  DevIconTrisquelGNULinux = '🐧',
  DevIconUbuntu = '🦸‍♂️',
  DevIconVanillaOS = '🍦',
  DevIconVoid = '🐧',
  DevIconWindows = '🪟',
  DevIconXeroLinux = '🐧',
  DevIconZorin = '⚡',
  DevIconopenSUSE = '🐧',
  DevIconpostmarketOS = '📱',
  DevIconBudgie = '🌿',
  DevIconCinnamon = '🍩',
  DevIconGNOME = '👤',
  DevIconLXDE = '💻',
  DevIconLXQt = '💻',
  DevIconMATE = '🌿',
  DevIconXfce = '💻',
  -- DevIconBSPWM = '🖥️',
  DevIconEnlightenment = '🌟',
  DevIconFluxbox = '💻',
  -- DevIconHyprland = '✨',
  -- DevIconJWM = '🖥️',
  DevIconQtile = '🎮',
  DevIconSway = '🌐',
  DevIconawesome = '⚡',
  DevIcondwm = '🖥️',
  -- DevIconi3 = '🐧',
  -- DevIconxmonad = '💻',
}

local function set_emoji_icons()
  local icons = nvim_web_devicon.get_icons()

  icons['avif'].icon = emoji.DevIconAvif
  icons['sxhkdrc'].icon = emoji.DevIconBSPWM
  icons['bspwmrc'].icon = emoji.DevIconBSPWM
  icons['.babelrc'].icon = emoji.DevIconBabelrc
  icons['.bash_profile'].icon = emoji.DevIconBashProfile
  icons['.bashrc'].icon = emoji.DevIconBashrc
  icons['build'].icon = emoji.DevIconBazelBuild
  icons['workspace'].icon = emoji.DevIconBazelWorkspace
  icons['brewfile'].icon = emoji.DevIconBrewfile
  icons['cmakelists.txt'].icon = emoji.DevIconCMakeLists
  icons['cantorrc'].icon = emoji.DevIconCantorrc
  icons['checkhealth'].icon = emoji.DevIconCheckhealth
  icons['code_of_conduct.md'].icon = emoji.DevIconCodeOfConduct
  icons['code_of_conduct'].icon = emoji.DevIconCodeOfConduct
  icons['commitlint.config.ts'].icon = emoji.DevIconCommitlintConfig
  icons['commitlint.config.js'].icon = emoji.DevIconCommitlintConfig
  icons['config'].icon = emoji.DevIconConfig
  icons['containerfile'].icon = emoji.DevIconDockerfile
  icons['.dockerignore'].icon = emoji.DevIconDockerfile
  icons['dockerfile'].icon = emoji.DevIconDockerfile
  icons['compose.yaml'].icon = emoji.DevIconDockerfile
  icons['compose.yml'].icon = emoji.DevIconDockerfile
  icons['docker-compose.yaml'].icon = emoji.DevIconDockerfile
  icons['docker-compose.yml'].icon = emoji.DevIconDockerfile
  icons['.ds_store'].icon = emoji.DevIconDsStore
  icons['.editorconfig'].icon = emoji.DevIconEditorConfig
  icons['.env'].icon = emoji.DevIconEnv
  icons['.eslintignore'].icon = emoji.DevIconEslintIgnore
  icons['eslint.config.mjs'].icon = emoji.DevIconEslintrc
  icons['.eslintrc'].icon = emoji.DevIconEslintrc
  icons['eslint.config.ts'].icon = emoji.DevIconEslintrc
  icons['eslint.config.js'].icon = emoji.DevIconEslintrc
  icons['eslint.config.cjs'].icon = emoji.DevIconEslintrc
  icons['favicon.ico'].icon = emoji.DevIconFavicon
  -- icons['freecad.conf'].icon = emoji.DevIconFreeCADConfig
  icons['gtkrc'].icon = emoji.DevIconGTK
  icons['.gtkrc-2.0'].icon = emoji.DevIconGTK
  icons['gemfile$'].icon = emoji.DevIconGemfile
  icons['.gitattributes'].icon = emoji.DevIconGitAttributes
  icons['.git-blame-ignore-revs'].icon = emoji.DevIconGitBlameIgnore
  icons['commit_editmsg'].icon = emoji.DevIconGitCommit
  icons['.gitconfig'].icon = emoji.DevIconGitConfig
  icons['.gitignore'].icon = emoji.DevIconGitIgnore
  icons['.gitmodules'].icon = emoji.DevIconGitModules
  icons['.gitlab-ci.yml'].icon = emoji.DevIconGitlabCI
  icons['go.mod'].icon = emoji.DevIconGoMod
  icons['go.sum'].icon = emoji.DevIconGoSum
  icons['go.work'].icon = emoji.DevIconGoWork
  icons['build.gradle'].icon = emoji.DevIconGradleBuildScript
  icons['gradle.properties'].icon = emoji.DevIconGradleProperties
  icons['settings.gradle'].icon = emoji.DevIconGradleSettings
  icons['gradle-wrapper.properties'].icon = emoji.DevIconGradleWrapperProperties
  icons['gradlew'].icon = emoji.DevIconGradleWrapperScript
  icons['groovy'].icon = emoji.DevIconGroovy
  icons['gruntfile.coffee'].icon = emoji.DevIconGruntfile
  icons['gruntfile.babel.js'].icon = emoji.DevIconGruntfile
  icons['gruntfile.ts'].icon = emoji.DevIconGruntfile
  icons['gruntfile.js'].icon = emoji.DevIconGruntfile
  icons['gulpfile.babel.js'].icon = emoji.DevIconGulpfile
  icons['gulpfile.coffee'].icon = emoji.DevIconGulpfile
  icons['gulpfile.ts'].icon = emoji.DevIconGulpfile
  icons['gulpfile.js'].icon = emoji.DevIconGulpfile
  icons['_gvimrc'].icon = emoji.DevIconGvimrc
  icons['.gvimrc'].icon = emoji.DevIconGvimrc
  icons['hypridle.conf'].icon = emoji.DevIconHypridle
  icons['hyprland.conf'].icon = emoji.DevIconHyprland
  icons['hyprlock.conf'].icon = emoji.DevIconHyprlock
  icons['hyprpaper.conf'].icon = emoji.DevIconHyprpaper
  icons['i18n.config.ts'].icon = emoji.DevIconI18nConfig
  icons['i18n.config.js'].icon = emoji.DevIconI18nConfig
  icons['ionic.config.json'].icon = emoji.DevIconIonic
  icons['.justfile'].icon = emoji.DevIconJustfile
  icons['justfile'].icon = emoji.DevIconJustfile
  icons['kdeglobals'].icon = emoji.DevIconKDEglobals
  icons['kalgebrarc'].icon = emoji.DevIconKalgebrarc
  icons['kdenlive-layoutsrc'].icon = emoji.DevIconKdenliveLayoutsrc
  icons['kdenliverc'].icon = emoji.DevIconKdenliverc
  icons['fp-info-cache'].icon = emoji.DevIconKiCadCache
  icons['fp-lib-table'].icon = emoji.DevIconKiCadFootprintTable
  icons['sym-lib-table'].icon = emoji.DevIconKiCadSymbolTable
  icons['kritadisplayrc'].icon = emoji.DevIconKritadisplayrc
  icons['kritarc'].icon = emoji.DevIconKritarc
  icons['lxde-rc.xml'].icon = emoji.DevIconLXDEConfigFile
  icons['lxqt.conf'].icon = emoji.DevIconLXQtConfigFile
  -- icons['license'].icon = emoji.DevIconLicense
  icons['license.md'].icon = emoji.DevIconLicense
  icons['copying'].icon = emoji.DevIconLicense
  icons['unlicense'].icon = emoji.DevIconLicense
  icons['copying.lesser'].icon = emoji.DevIconLicense
  icons['.luaurc'].icon = emoji.DevIconLuaurc
  icons['.mailmap'].icon = emoji.DevIconMailmap
  -- icons['makefile'].icon = emoji.DevIconMakefile
  -- icons['gnumakefile'].icon = emoji.DevIconMakefile
  icons['pom.xml'].icon = emoji.DevIconMaven
  icons['mix.lock'].icon = emoji.DevIconMixLock
  icons['mpv.conf'].icon = emoji.DevIconMpv
  icons['.npmignore'].icon = emoji.DevIconNPMIgnore
  icons['.npmrc'].icon = emoji.DevIconNPMrc
  icons['node_modules'].icon = emoji.DevIconNodeModules
  icons['.nuxtrc'].icon = emoji.DevIconNuxtConfig
  icons['nuxt.config.js'].icon = emoji.DevIconNuxtConfig
  icons['nuxt.config.mjs'].icon = emoji.DevIconNuxtConfig
  icons['nuxt.config.ts'].icon = emoji.DevIconNuxtConfig
  icons['nuxt.config.cjs'].icon = emoji.DevIconNuxtConfig
  -- icons['pkgbuild'].icon = emoji.DevIconPKGBUILD
  icons['package.json'].icon = emoji.DevIconPackageJson
  icons['package-lock.json'].icon = emoji.DevIconPackageLockJson
  icons['platformio.ini'].icon = emoji.DevIconPlatformio
  icons['.prettierrc.json5'].icon = emoji.DevIconPrettierConfig
  icons['.prettierrc'].icon = emoji.DevIconPrettierConfig
  icons['prettier.config.cjs'].icon = emoji.DevIconPrettierConfig
  icons['prettier.config.js'].icon = emoji.DevIconPrettierConfig
  icons['prettier.config.ts'].icon = emoji.DevIconPrettierConfig
  icons['prettier.config.mjs'].icon = emoji.DevIconPrettierConfig
  icons['.prettierrc.js'].icon = emoji.DevIconPrettierConfig
  icons['.prettierrc.toml'].icon = emoji.DevIconPrettierConfig
  icons['.prettierrc.json'].icon = emoji.DevIconPrettierConfig
  icons['.prettierrc.mjs'].icon = emoji.DevIconPrettierConfig
  icons['.prettierrc.cjs'].icon = emoji.DevIconPrettierConfig
  icons['.prettierrc.yaml'].icon = emoji.DevIconPrettierConfig
  icons['.prettierrc.yml'].icon = emoji.DevIconPrettierConfig
  icons['.prettierignore'].icon = emoji.DevIconPrettierIgnore
  icons['procfile'].icon = emoji.DevIconProcfile
  -- icons['prusaslicergcodeviewer.ini'].icon = emoji.DevIconPrusaSlicer
  -- icons['prusaslicer.ini'].icon = emoji.DevIconPrusaSlicer
  icons['py.typed'].icon = emoji.DevIconPy
  -- icons['qtproject.conf'].icon = emoji.DevIconQt
  icons['rakefile'].icon = emoji.DevIconRakefile
  -- icons['rmd'].icon = emoji.DevIconRmd
  icons['robots.txt'].icon = emoji.DevIconRobotsTxt
  -- icons['.srcinfo'].icon = emoji.DevIconSRCINFO
  icons['security'].icon = emoji.DevIconSecurity
  icons['security.md'].icon = emoji.DevIconSecurity
  icons['.settings.json'].icon = emoji.DevIconSettingsJson
  icons['svelte.config.js'].icon = emoji.DevIconSvelteConfig
  icons['tsconfig.json'].icon = emoji.DevIconTSConfig
  icons['tailwind.config.ts'].icon = emoji.DevIconTailwindConfig
  icons['tailwind.config.mjs'].icon = emoji.DevIconTailwindConfig
  icons['tailwind.config.js'].icon = emoji.DevIconTailwindConfig
  icons['tmux.conf'].icon = emoji.DevIconTmux
  icons['tmux.conf.local'].icon = emoji.DevIconTmux
  icons['ext_typoscript_setup.txt'].icon = emoji.DevIconTypoScriptSetup
  icons['vlcrc'].icon = emoji.DevIconVLC
  icons['vagrantfile$'].icon = emoji.DevIconVagrantfile
  icons['vercel.json'].icon = emoji.DevIconVercel
  icons['.vimrc'].icon = emoji.DevIconVimrc
  icons['_vimrc'].icon = emoji.DevIconVimrc
  -- icons['webpack'].icon = emoji.DevIconWebpack
  icons['weston.ini'].icon = emoji.DevIconWeston
  icons['.xinitrc'].icon = emoji.DevIconXInitrc
  icons['xsettingsd.conf'].icon = emoji.DevIconXSettingsdConf
  -- icons['.xauthority'].icon = emoji.DevIconXauthority
  icons['xorg.conf'].icon = emoji.DevIconXorgConf
  -- icons['.xresources'].icon = emoji.DevIconXresources
  icons['.xsession'].icon = emoji.DevIconXsession
  icons['build.zig.zon'].icon = emoji.DevIconZigObjectNotation
  icons['.zshenv'].icon = emoji.DevIconZshenv
  icons['.zprofile'].icon = emoji.DevIconZshprofile
  icons['.zshrc'].icon = emoji.DevIconZshrc
  icons['i3blocks.conf'].icon = emoji.DevIconi3
  icons['i3status.conf'].icon = emoji.DevIconi3
  icons['.nvmrc'].icon = emoji.DevIconnode
  -- icons['xmonad.hs'].icon = emoji.DevIconxmonad
  icons['xmobarrc.hs'].icon = emoji.DevIconxmonad
  icons['xmobarrc'].icon = emoji.DevIconxmonad
  icons['stl'].icon = emoji.DevIcon3DObjectFile
  icons['fbx'].icon = emoji.DevIcon3DObjectFile
  icons['obj'].icon = emoji.DevIcon3DObjectFile
  icons['ply'].icon = emoji.DevIcon3DObjectFile
  icons['3mf'].icon = emoji.DevIcon3DObjectFile
  icons['3gp'].icon = emoji.DevIcon3gp
  icons['7z'].icon = emoji.DevIcon7z
  icons['apl'].icon = emoji.DevIconAPL
  icons['aac'].icon = emoji.DevIconAdvancedAudioCoding
  icons['ai'].icon = emoji.DevIconAi
  icons['android'].icon = emoji.DevIconAndroid
  icons['app'].icon = emoji.DevIconApp
  icons['applescript'].icon = emoji.DevIconAppleScript
  icons['ino'].icon = emoji.DevIconArduino
  icons['asc'].icon = emoji.DevIconAsc
  icons['cast'].icon = emoji.DevIconAsciinema
  icons['ass'].icon = emoji.DevIconAss
  icons['astro'].icon = emoji.DevIconAstro
  icons['aif'].icon = emoji.DevIconAudioInterchangeFileFormat
  icons['aiff'].icon = emoji.DevIconAudioInterchangeFileFormat
  icons['dwg'].icon = emoji.DevIconAutoCADDwg
  icons['dxf'].icon = emoji.DevIconAutoCADDxf
  icons['awk'].icon = emoji.DevIconAwk
  icons['azcli'].icon = emoji.DevIconAzureCli
  icons['bqn'].icon = emoji.DevIconBQN
  icons['bak'].icon = emoji.DevIconBackup
  icons['bash'].icon = emoji.DevIconBash
  icons['bat'].icon = emoji.DevIconBat
  icons['bazel'].icon = emoji.DevIconBazel
  icons['bib'].icon = emoji.DevIconBibTeX
  icons['bicep'].icon = emoji.DevIconBicep
  icons['bicepparam'].icon = emoji.DevIconBicepParameters
  icons['bin'].icon = emoji.DevIconBin
  icons['glb'].icon = emoji.DevIconBinaryGLTF
  icons['blade.php'].icon = emoji.DevIconBlade
  icons['blend'].icon = emoji.DevIconBlender
  icons['blp'].icon = emoji.DevIconBlueprint
  icons['bmp'].icon = emoji.DevIconBmp
  icons['brep'].icon = emoji.DevIconBoundaryRepresentation
  icons['bz'].icon = emoji.DevIconBz
  icons['bz2'].icon = emoji.DevIconBz2
  icons['bz3'].icon = emoji.DevIconBz3
  icons['bzl'].icon = emoji.DevIconBzl
  icons['c'].icon = emoji.DevIconC
  icons['cmake'].icon = emoji.DevIconCMake
  icons['c++'].icon = emoji.DevIconCPlusPlus
  icons['cc'].icon = emoji.DevIconCPlusPlus
  icons['ccm'].icon = emoji.DevIconCPlusPlusModule
  icons['csproj'].icon = emoji.DevIconCSharpProject
  icons['cache'].icon = emoji.DevIconCache
  icons['cjs'].icon = emoji.DevIconCjs
  icons['clj'].icon = emoji.DevIconClojure
  icons['cljc'].icon = emoji.DevIconClojureC
  icons['cljd'].icon = emoji.DevIconClojureDart
  icons['cljs'].icon = emoji.DevIconClojureJS
  icons['cbl'].icon = emoji.DevIconCobol
  icons['cobol'].icon = emoji.DevIconCobol
  icons['cpy'].icon = emoji.DevIconCobol
  icons['cob'].icon = emoji.DevIconCobol
  icons['coffee'].icon = emoji.DevIconCoffee
  icons['conf'].icon = emoji.DevIconConf
  icons['config.ru'].icon = emoji.DevIconConfigRu
  icons['cfg'].icon = emoji.DevIconConfiguration
  icons['cow'].icon = emoji.DevIconCowsayFile
  icons['cp'].icon = emoji.DevIconCp
  icons['cpp'].icon = emoji.DevIconCpp
  icons['cppm'].icon = emoji.DevIconCppm
  icons['crdownload'].icon = emoji.DevIconCrdownload
  icons['cr'].icon = emoji.DevIconCrystal
  icons['cs'].icon = emoji.DevIconCs
  icons['csh'].icon = emoji.DevIconCsh
  icons['cson'].icon = emoji.DevIconCson
  icons['css'].icon = emoji.DevIconCss
  icons['csv'].icon = emoji.DevIconCsv
  icons['cts'].icon = emoji.DevIconCts
  icons['cue'].icon = emoji.DevIconCue
  icons['cxx'].icon = emoji.DevIconCxx
  icons['cxxm'].icon = emoji.DevIconCxxm
  icons['d'].icon = emoji.DevIconD
  icons['dart'].icon = emoji.DevIconDart
  icons['db'].icon = emoji.DevIconDb
  icons['dconf'].icon = emoji.DevIconDconf
  icons['desktop'].icon = emoji.DevIconDesktopEntry
  icons['diff'].icon = emoji.DevIconDiff
  icons['dll'].icon = emoji.DevIconDll
  icons['doc'].icon = emoji.DevIconDoc
  icons['Dockerfile'].icon = emoji.DevIconDockerfile
  icons['docx'].icon = emoji.DevIconDocx
  icons['dot'].icon = emoji.DevIconDot
  icons['download'].icon = emoji.DevIconDownload
  icons['drl'].icon = emoji.DevIconDrools
  icons['dropbox'].icon = emoji.DevIconDropbox
  icons['dump'].icon = emoji.DevIconDump
  icons['ebook'].icon = emoji.DevIconEbook
  icons['edn'].icon = emoji.DevIconEdn
  icons['eex'].icon = emoji.DevIconEex
  icons['ejs'].icon = emoji.DevIconEjs
  icons['elf'].icon = emoji.DevIconElf
  icons['elc'].icon = emoji.DevIconElisp
  icons['el'].icon = emoji.DevIconElisp
  icons['eln'].icon = emoji.DevIconElisp
  icons['elm'].icon = emoji.DevIconElm
  icons['eot'].icon = emoji.DevIconEmbeddedOpenTypeFont
  icons['env'].icon = emoji.DevIconEnv
  icons['epp'].icon = emoji.DevIconEpp
  icons['epub'].icon = emoji.DevIconEpub
  icons['erb'].icon = emoji.DevIconErb
  icons['erl'].icon = emoji.DevIconErl
  icons['ex'].icon = emoji.DevIconEx
  icons['exe'].icon = emoji.DevIconExe
  icons['exs'].icon = emoji.DevIconExs
  icons['flc'].icon = emoji.DevIconFIGletFontControl
  icons['flf'].icon = emoji.DevIconFIGletFontFormat
  icons['fdmdownload'].icon = emoji.DevIconFdmdownload
  icons['fnl'].icon = emoji.DevIconFennel
  icons['fish'].icon = emoji.DevIconFish
  icons['f90'].icon = emoji.DevIconFortran
  icons['fcparam'].icon = emoji.DevIconFreeCAD
  icons['fcmat'].icon = emoji.DevIconFreeCAD
  icons['fcmacro'].icon = emoji.DevIconFreeCAD
  icons['fctl'].icon = emoji.DevIconFreeCAD
  icons['fcbak'].icon = emoji.DevIconFreeCAD
  icons['fcstd'].icon = emoji.DevIconFreeCAD
  icons['fctb'].icon = emoji.DevIconFreeCAD
  icons['fcstd1'].icon = emoji.DevIconFreeCAD
  icons['fcscript'].icon = emoji.DevIconFreeCAD
  icons['flac'].icon = emoji.DevIconFreeLosslessAudioCodec
  icons['fs'].icon = emoji.DevIconFs
  icons['f#'].icon = emoji.DevIconFsharp
  icons['fsi'].icon = emoji.DevIconFsi
  icons['fsscript'].icon = emoji.DevIconFsscript
  icons['fsx'].icon = emoji.DevIconFsx
  icons['f3d'].icon = emoji.DevIconFusion360
  icons['gcode'].icon = emoji.DevIconGCode
  icons['gd'].icon = emoji.DevIconGDScript
  icons['xcf'].icon = emoji.DevIconGIMP
  icons['gresource'].icon = emoji.DevIconGTK
  icons['gemspec'].icon = emoji.DevIconGemspec
  icons['ebuild'].icon = emoji.DevIconGentooBuild
  icons['gif'].icon = emoji.DevIconGif
  icons['git'].icon = emoji.DevIconGitLogo
  icons['gleam'].icon = emoji.DevIconGleam
  icons['go'].icon = emoji.DevIconGo
  icons['godot'].icon = emoji.DevIconGodotProject
  icons['tres'].icon = emoji.DevIconGodotTextResource
  icons['tscn'].icon = emoji.DevIconGodotTextScene
  icons['gradle'].icon = emoji.DevIconGradle
  icons['gql'].icon = emoji.DevIconGraphQL
  icons['graphql'].icon = emoji.DevIconGraphQL
  icons['gv'].icon = emoji.DevIconGv
  icons['gz'].icon = emoji.DevIconGz
  icons['h'].icon = emoji.DevIconH
  icons['http'].icon = emoji.DevIconHTTP
  icons['haml'].icon = emoji.DevIconHaml
  icons['hx'].icon = emoji.DevIconHaxe
  icons['hbs'].icon = emoji.DevIconHbs
  icons['heex'].icon = emoji.DevIconHeex
  icons['hex'].icon = emoji.DevIconHexadecimal
  icons['hh'].icon = emoji.DevIconHh
  icons['hpp'].icon = emoji.DevIconHpp
  icons['hrl'].icon = emoji.DevIconHrl
  icons['hs'].icon = emoji.DevIconHs
  icons['htm'].icon = emoji.DevIconHtm
  icons['html'].icon = emoji.DevIconHtml
  icons['huff'].icon = emoji.DevIconHuff
  icons['hurl'].icon = emoji.DevIconHurl
  icons['hxx'].icon = emoji.DevIconHxx
  icons['ical'].icon = emoji.DevIconIcal
  icons['icalendar'].icon = emoji.DevIconIcalendar
  icons['ico'].icon = emoji.DevIconIco
  icons['ics'].icon = emoji.DevIconIcs
  icons['ifb'].icon = emoji.DevIconIfb
  icons['ifc'].icon = emoji.DevIconIfc
  icons['ige'].icon = emoji.DevIconIge
  icons['iges'].icon = emoji.DevIconIges
  icons['igs'].icon = emoji.DevIconIgs
  icons['image'].icon = emoji.DevIconImage
  icons['img'].icon = emoji.DevIconImg
  icons['import'].icon = emoji.DevIconImportConfiguration
  icons['info'].icon = emoji.DevIconInfo
  icons['ini'].icon = emoji.DevIconIni
  icons['iso'].icon = emoji.DevIconIso
  icons['ixx'].icon = emoji.DevIconIxx
  icons['jwmrc'].icon = emoji.DevIconJWM
  icons['java'].icon = emoji.DevIconJava
  icons['spec.jsx'].icon = emoji.DevIconJavaScriptReactSpec
  icons['test.jsx'].icon = emoji.DevIconJavaScriptReactTest
  icons['jl'].icon = emoji.DevIconJl
  icons['jpeg'].icon = emoji.DevIconJpeg
  icons['jxl'].icon = emoji.DevIconJpegXl
  icons['jpg'].icon = emoji.DevIconJpg
  icons['js'].icon = emoji.DevIconJs
  icons['json'].icon = emoji.DevIconJson
  icons['json5'].icon = emoji.DevIconJson5
  icons['jsonc'].icon = emoji.DevIconJsonc
  icons['jsx'].icon = emoji.DevIconJsx
  icons['kbx'].icon = emoji.DevIconKbx
  icons['kdb'].icon = emoji.DevIconKdb
  icons['kdbx'].icon = emoji.DevIconKdbx
  icons['kdenlivetitle'].icon = emoji.DevIconKdenlive
  icons['kdenlive'].icon = emoji.DevIconKdenlive
  icons['kicad_sch'].icon = emoji.DevIconKiCad
  icons['kicad_prl'].icon = emoji.DevIconKiCad
  icons['kicad_pro'].icon = emoji.DevIconKiCad
  icons['kicad_mod'].icon = emoji.DevIconKiCad
  icons['kicad_sym'].icon = emoji.DevIconKiCad
  icons['kicad_wks'].icon = emoji.DevIconKiCad
  icons['kicad_pcb'].icon = emoji.DevIconKiCad
  icons['kicad_dru'].icon = emoji.DevIconKiCad
  icons['kt'].icon = emoji.DevIconKotlin
  icons['kts'].icon = emoji.DevIconKotlinScript
  icons['kpp'].icon = emoji.DevIconKrita
  icons['krz'].icon = emoji.DevIconKrita
  icons['kra'].icon = emoji.DevIconKrita
  icons['ksh'].icon = emoji.DevIconKsh
  icons['leex'].icon = emoji.DevIconLeex
  icons['less'].icon = emoji.DevIconLess
  icons['lhs'].icon = emoji.DevIconLhs
  icons['lib'].icon = emoji.DevIconLib
  icons['lff'].icon = emoji.DevIconLibrecadFontFile
  icons['license'].icon = emoji.DevIconLicense
  icons['ko'].icon = emoji.DevIconLinuxKernelObject
  icons['liquid'].icon = emoji.DevIconLiquid
  icons['pot'].icon = emoji.DevIconLocalization
  icons['qm'].icon = emoji.DevIconLocalization
  icons['po'].icon = emoji.DevIconLocalization
  icons['strings'].icon = emoji.DevIconLocalization
  icons['lck'].icon = emoji.DevIconLock
  icons['lock'].icon = emoji.DevIconLock
  icons['log'].icon = emoji.DevIconLog
  icons['xm'].icon = emoji.DevIconLogos
  icons['x'].icon = emoji.DevIconLogos
  icons['lrc'].icon = emoji.DevIconLrc
  icons['luac'].icon = emoji.DevIconLua
  icons['lua'].icon = emoji.DevIconLua
  icons['luau'].icon = emoji.DevIconLuau
  icons['m3u'].icon = emoji.DevIconM3u
  icons['m3u8'].icon = emoji.DevIconM3u8
  icons['m4v'].icon = emoji.DevIconM4V
  icons['mov'].icon = emoji.DevIconMOV
  icons['m4a'].icon = emoji.DevIconMPEG4
  icons['mp3'].icon = emoji.DevIconMPEGAudioLayerIII
  icons['magnet'].icon = emoji.DevIconMagnet
  icons['makefile'].icon = emoji.DevIconMakefile
  icons['mk'].icon = emoji.DevIconMakefile
  icons['gnumakefile'].icon = emoji.DevIconMakefile
  icons['markdown'].icon = emoji.DevIconMarkdown
  icons['material'].icon = emoji.DevIconMaterial
  icons['md'].icon = emoji.DevIconMd
  icons['md5'].icon = emoji.DevIconMd5
  icons['mdx'].icon = emoji.DevIconMdx
  icons['mint'].icon = emoji.DevIconMint
  icons['mjs'].icon = emoji.DevIconMjs
  icons['mkv'].icon = emoji.DevIconMkv
  icons['ml'].icon = emoji.DevIconMl
  icons['mli'].icon = emoji.DevIconMli
  icons['mobi'].icon = emoji.DevIconMobi
  icons['🔥'].icon = emoji.DevIconMojo
  icons['mojo'].icon = emoji.DevIconMojo
  icons['ape'].icon = emoji.DevIconMonkeysAudio
  icons['mo'].icon = emoji.DevIconMotoko
  icons['mp4'].icon = emoji.DevIconMp4
  icons['mpp'].icon = emoji.DevIconMpp
  icons['mts'].icon = emoji.DevIconMts
  icons['mustache'].icon = emoji.DevIconMustache
  icons['nfo'].icon = emoji.DevIconNfo
  icons['nim'].icon = emoji.DevIconNim
  icons['nix'].icon = emoji.DevIconNix
  icons['ipynb'].icon = emoji.DevIconNotebook
  icons['nswag'].icon = emoji.DevIconNswag
  icons['nu'].icon = emoji.DevIconNushell
  icons['o'].icon = emoji.DevIconObjectFile
  icons['m'].icon = emoji.DevIconObjectiveC
  icons['mm'].icon = emoji.DevIconObjectiveCPlusPlus
  icons['ogg'].icon = emoji.DevIconOggVorbis
  icons['scad'].icon = emoji.DevIconOpenSCAD
  icons['otf'].icon = emoji.DevIconOpenTypeFont
  icons['opus'].icon = emoji.DevIconOpusAudioFile
  icons['org'].icon = emoji.DevIconOrgMode
  icons['out'].icon = emoji.DevIconOut
  icons['pck'].icon = emoji.DevIconPackedResource
  icons['part'].icon = emoji.DevIconPart
  icons['patch'].icon = emoji.DevIconPatch
  icons['pdf'].icon = emoji.DevIconPdf
  icons['php'].icon = emoji.DevIconPhp
  icons['pl'].icon = emoji.DevIconPl
  icons['pls'].icon = emoji.DevIconPls
  icons['pm'].icon = emoji.DevIconPm
  icons['png'].icon = emoji.DevIconPng
  icons['pp'].icon = emoji.DevIconPp
  icons['ppt'].icon = emoji.DevIconPpt
  icons['prisma'].icon = emoji.DevIconPrisma
  icons['pro'].icon = emoji.DevIconProlog
  icons['psd1'].icon = emoji.DevIconPsManifestfile
  icons['psm1'].icon = emoji.DevIconPsScriptModulefile
  icons['ps1'].icon = emoji.DevIconPsScriptfile
  icons['psb'].icon = emoji.DevIconPsb
  icons['psd'].icon = emoji.DevIconPsd
  icons['pub'].icon = emoji.DevIconPub
  icons['pcm'].icon = emoji.DevIconPulseCodeModulation
  icons['pxd'].icon = emoji.DevIconPxd
  icons['pxi'].icon = emoji.DevIconPxi
  icons['py'].icon = emoji.DevIconPy
  icons['pyc'].icon = emoji.DevIconPyc
  icons['pyd'].icon = emoji.DevIconPyd
  icons['pyi'].icon = emoji.DevIconPyi
  icons['pyo'].icon = emoji.DevIconPyo
  icons['pyw'].icon = emoji.DevIconPyw
  icons['pyx'].icon = emoji.DevIconPyx
  icons['qss'].icon = emoji.DevIconQt
  icons['qml'].icon = emoji.DevIconQt
  icons['qrc'].icon = emoji.DevIconQt
  icons['query'].icon = emoji.DevIconQuery
  icons['r'].icon = emoji.DevIconR
  icons['R'].icon = emoji.DevIconR
  icons['rake'].icon = emoji.DevIconRake
  icons['rar'].icon = emoji.DevIconRar
  icons['razor'].icon = emoji.DevIconRazorPage
  icons['cshtml'].icon = emoji.DevIconRazorPage
  icons['rb'].icon = emoji.DevIconRb
  icons['res'].icon = emoji.DevIconReScript
  icons['resi'].icon = emoji.DevIconReScriptInterface
  icons['rlib'].icon = emoji.DevIconRlib
  icons['rmd'].icon = emoji.DevIconRmd
  icons['rproj'].icon = emoji.DevIconRproj
  icons['rs'].icon = emoji.DevIconRs
  icons['rss'].icon = emoji.DevIconRss
  icons['sass'].icon = emoji.DevIconSass
  icons['scala'].icon = emoji.DevIconScala
  icons['sc'].icon = emoji.DevIconScalaScript
  icons['scm'].icon = emoji.DevIconScheme
  icons['scss'].icon = emoji.DevIconScss
  icons['sh'].icon = emoji.DevIconSh
  icons['sha1'].icon = emoji.DevIconSha1
  icons['sha224'].icon = emoji.DevIconSha224
  icons['sha256'].icon = emoji.DevIconSha256
  icons['sha384'].icon = emoji.DevIconSha384
  icons['sha512'].icon = emoji.DevIconSha512
  icons['so'].icon = emoji.DevIconSharedObject
  icons['sig'].icon = emoji.DevIconSig
  icons['signature'].icon = emoji.DevIconSignature
  icons['skp'].icon = emoji.DevIconSketchUp
  icons['slim'].icon = emoji.DevIconSlim
  icons['sln'].icon = emoji.DevIconSln
  icons['sml'].icon = emoji.DevIconSml
  icons['sldasm'].icon = emoji.DevIconSolidWorksAsm
  icons['sldprt'].icon = emoji.DevIconSolidWorksPrt
  icons['sol'].icon = emoji.DevIconSolidity
  icons['slvs'].icon = emoji.DevIconSolveSpace
  icons['spec.js'].icon = emoji.DevIconSpecJs
  icons['spec.ts'].icon = emoji.DevIconSpecTs
  icons['sqlite'].icon = emoji.DevIconSql
  icons['sqlite3'].icon = emoji.DevIconSql
  icons['sql'].icon = emoji.DevIconSql
  icons['srt'].icon = emoji.DevIconSrt
  icons['ssa'].icon = emoji.DevIconSsa
  icons['a'].icon = emoji.DevIconStaticLibraryArchive
  icons['ste'].icon = emoji.DevIconSte
  icons['step'].icon = emoji.DevIconStep
  icons['stp'].icon = emoji.DevIconStp
  icons['styl'].icon = emoji.DevIconStyl
  icons['sub'].icon = emoji.DevIconSub
  icons['sublime'].icon = emoji.DevIconSublime
  icons['suo'].icon = emoji.DevIconSuo
  icons['svelte'].icon = emoji.DevIconSvelte
  icons['svg'].icon = emoji.DevIconSvg
  icons['swift'].icon = emoji.DevIconSwift
  icons['sv'].icon = emoji.DevIconSystemVerilog
  icons['svh'].icon = emoji.DevIconSystemVerilog
  icons['tfvars'].icon = emoji.DevIconTFVars
  icons['tbc'].icon = emoji.DevIconTcl
  icons['tcl'].icon = emoji.DevIconTcl
  icons['templ'].icon = emoji.DevIconTempl
  icons['terminal'].icon = emoji.DevIconTerminal
  icons['tf'].icon = emoji.DevIconTerraform
  icons['test.js'].icon = emoji.DevIconTestJs
  icons['test.ts'].icon = emoji.DevIconTestTs
  icons['tex'].icon = emoji.DevIconTex
  icons['tgz'].icon = emoji.DevIconTgz
  icons['msf'].icon = emoji.DevIconThunderbird
  icons['tmux'].icon = emoji.DevIconTmux
  icons['toml'].icon = emoji.DevIconToml
  icons['t'].icon = emoji.DevIconTor
  icons['torrent'].icon = emoji.DevIconTorrent
  icons['ttf'].icon = emoji.DevIconTrueTypeFont
  icons['tsx'].icon = emoji.DevIconTsx
  icons['twig'].icon = emoji.DevIconTwig
  icons['txt'].icon = emoji.DevIconTxt
  icons['txz'].icon = emoji.DevIconTxz
  icons['ts'].icon = emoji.DevIconTypeScript
  icons['d.ts'].icon = emoji.DevIconTypeScriptDeclaration
  icons['spec.tsx'].icon = emoji.DevIconTypeScriptReactSpec
  icons['test.tsx'].icon = emoji.DevIconTypeScriptReactTest
  icons['typoscript'].icon = emoji.DevIconTypoScript
  icons['tsconfig'].icon = emoji.DevIconTypoScriptConfig
  icons['ui'].icon = emoji.DevIconUI
  icons['vhd'].icon = emoji.DevIconVHDL
  icons['vhdl'].icon = emoji.DevIconVHDL
  icons['wrz'].icon = emoji.DevIconVRML
  icons['wrl'].icon = emoji.DevIconVRML
  icons['vala'].icon = emoji.DevIconVala
  icons['vh'].icon = emoji.DevIconVerilog
  icons['v'].icon = emoji.DevIconVerilog
  icons['vim'].icon = emoji.DevIconVim
  icons['vsh'].icon = emoji.DevIconVlang
  icons['vsix'].icon = emoji.DevIconVsix
  icons['vue'].icon = emoji.DevIconVue
  icons['wasm'].icon = emoji.DevIconWasm
  icons['wv'].icon = emoji.DevIconWavPack
  icons['wvc'].icon = emoji.DevIconWavPackCorrection
  icons['wav'].icon = emoji.DevIconWaveformAudioFile
  icons['woff'].icon = emoji.DevIconWebOpenFontFormat
  icons['woff2'].icon = emoji.DevIconWebOpenFontFormat
  icons['webm'].icon = emoji.DevIconWebm
  icons['webmanifest'].icon = emoji.DevIconWebmanifest
  icons['webp'].icon = emoji.DevIconWebp
  icons['webpack'].icon = emoji.DevIconWebpack
  icons['wma'].icon = emoji.DevIconWindowsMediaAudio
  icons['xaml'].icon = emoji.DevIconXaml
  icons['xcstrings'].icon = emoji.DevIconXcLocalization
  icons['xcplayground'].icon = emoji.DevIconXcPlayground
  icons['xls'].icon = emoji.DevIconXls
  icons['xlsx'].icon = emoji.DevIconXlsx
  icons['xml'].icon = emoji.DevIconXml
  icons['xpi'].icon = emoji.DevIconXpi
  icons['xul'].icon = emoji.DevIconXul
  icons['xz'].icon = emoji.DevIconXz
  icons['yaml'].icon = emoji.DevIconYaml
  icons['yml'].icon = emoji.DevIconYml
  icons['zig'].icon = emoji.DevIconZig
  icons['zip'].icon = emoji.DevIconZip
  icons['zsh'].icon = emoji.DevIconZsh
  icons['zst'].icon = emoji.DevIconZst
  icons['apk'].icon = emoji.DevIconapk
  icons['cu'].icon = emoji.DevIconcuda
  icons['cuh'].icon = emoji.DevIconcudah
  icons['sbt'].icon = emoji.DevIconsbt
  icons['aosc'].icon = emoji.DevIconAOSC
  icons['alma'].icon = emoji.DevIconAlmalinux
  icons['alpine'].icon = emoji.DevIconAlpine
  icons['apple'].icon = emoji.DevIconApple
  icons['arch'].icon = emoji.DevIconArch
  icons['archcraft'].icon = emoji.DevIconArchcraft
  icons['archlabs'].icon = emoji.DevIconArchlabs
  icons['arcolinux'].icon = emoji.DevIconArcoLinux
  icons['artix'].icon = emoji.DevIconArtix
  icons['biglinux'].icon = emoji.DevIconBigLinux
  icons['centos'].icon = emoji.DevIconCentos
  icons['crystallinux'].icon = emoji.DevIconCrystalLinux
  icons['debian'].icon = emoji.DevIconDebian
  icons['deepin'].icon = emoji.DevIconDeepin
  icons['devuan'].icon = emoji.DevIconDevuan
  icons['elementary'].icon = emoji.DevIconElementary
  icons['endeavour'].icon = emoji.DevIconEndeavour
  icons['fedora'].icon = emoji.DevIconFedora
  icons['freebsd'].icon = emoji.DevIconFreeBSD
  icons['garuda'].icon = emoji.DevIconGarudaLinux
  icons['gentoo'].icon = emoji.DevIconGentoo
  icons['guix'].icon = emoji.DevIconGuix
  icons['hyperbola'].icon = emoji.DevIconHyperbolaGNULinuxLibre
  icons['illumos'].icon = emoji.DevIconIllumos
  icons['kdeneon'].icon = emoji.DevIconKDEneon
  icons['kali'].icon = emoji.DevIconKali
  icons['kubuntu'].icon = emoji.DevIconKubuntu
  icons['lxle'].icon = emoji.DevIconLXLE
  icons['linux'].icon = emoji.DevIconLinux
  icons['locos'].icon = emoji.DevIconLocOS
  icons['mxlinux'].icon = emoji.DevIconMXLinux
  icons['mageia'].icon = emoji.DevIconMageia
  icons['manjaro'].icon = emoji.DevIconManjaro
  icons['mint'].icon = emoji.DevIconMint
  icons['nixos'].icon = emoji.DevIconNixOS
  icons['openbsd'].icon = emoji.DevIconOpenBSD
  icons['parabola'].icon = emoji.DevIconParabolaGNULinuxLibre
  icons['parrot'].icon = emoji.DevIconParrot
  icons['pop_os'].icon = emoji.DevIconPop_OS
  icons['puppylinux'].icon = emoji.DevIconPuppyLinux
  icons['qubesos'].icon = emoji.DevIconQubesOS
  icons['raspberry_pi'].icon = emoji.DevIconRaspberryPiOS
  icons['redhat'].icon = emoji.DevIconRedhat
  icons['rocky'].icon = emoji.DevIconRockyLinux
  icons['sabayon'].icon = emoji.DevIconSabayon
  icons['slackware'].icon = emoji.DevIconSlackware
  icons['solus'].icon = emoji.DevIconSolus
  icons['tails'].icon = emoji.DevIconTails
  icons['trisquel'].icon = emoji.DevIconTrisquelGNULinux
  icons['ubuntu'].icon = emoji.DevIconUbuntu
  icons['vanillaos'].icon = emoji.DevIconVanillaOS
  icons['void'].icon = emoji.DevIconVoid
  icons['windows'].icon = emoji.DevIconWindows
  icons['xerolinux'].icon = emoji.DevIconXeroLinux
  icons['zorin'].icon = emoji.DevIconZorin
  icons['opensuse'].icon = emoji.DevIconopenSUSE
  icons['postmarketos'].icon = emoji.DevIconpostmarketOS
  icons['budgie'].icon = emoji.DevIconBudgie
  icons['cinnamon'].icon = emoji.DevIconCinnamon
  icons['gnome'].icon = emoji.DevIconGNOME
  icons['plasma'].icon = emoji.DevIconKDEPlasma
  icons['lxde'].icon = emoji.DevIconLXDE
  icons['lxqt'].icon = emoji.DevIconLXQt
  icons['mate'].icon = emoji.DevIconMATE
  icons['xfce'].icon = emoji.DevIconXfce
  icons['bspwm'].icon = emoji.DevIconBSPWM
  icons['enlightenment'].icon = emoji.DevIconEnlightenment
  icons['fluxbox'].icon = emoji.DevIconFluxbox
  icons['hyprland'].icon = emoji.DevIconHyprland
  icons['jwm'].icon = emoji.DevIconJWM
  icons['qtile'].icon = emoji.DevIconQtile
  icons['sway'].icon = emoji.DevIconSway
  icons['awesomewm'].icon = emoji.DevIconawesome
  icons['dwm'].icon = emoji.DevIcondwm
  icons['i3'].icon = emoji.DevIconi3
  icons['xmonad'].icon = emoji.DevIconxmonad
  return icons
end

local function assign_aphabet_icon(icons, file_name)
  local first_letter = string.sub(file_name, 1, 1):lower()
  if alphabet[first_letter] then
    icons[file_name].icon = alphabet[first_letter]
  end
end

local function set_alphabet_icons(font)
  local icons = nvim_web_devicon.get_icons()

  if font == 'black_square_font' then
    alphabet = black_square_font
  elseif font == 'square_font' then
    alphabet = square_font
  elseif font == 'bold_italic_font' then
    alphabet = bold_italic_font
  elseif font == 'double_struck_font' then
    alphabet = double_struck_font
  elseif font == 'fancy_style_17_font' then
    alphabet = fancy_style_17_font
  elseif font == 'fancy_style_19_font' then
    alphabet = fancy_style_19_font
  else
    alphabet = normal_font
  end

  for ext in pairs(icons) do
    assign_aphabet_icon(icons, ext)
  end
end

-- upload to github, then lazy

local function set_icons(style, font)
  local icons
  if style == 'alphabet' then
    icons = set_alphabet_icons(font)
    nvim_web_devicon.set_default_icon(' ', '#6d8086', 65)
  elseif style == 'emoji' then
    icons = set_emoji_icons()
    nvim_web_devicon.set_default_icon(emoji.DevIconDefault, '#6d8086', 65)
  end
  nvim_web_devicon.set_icon {
    icons,
  }
end
--
local function setup(style, font)
  set_icons(style, font)
end

return {
  setup = setup,
}
